"""
Django settings for set project.
Generated by 'django-admin startproject' using Django 5.0.
"""
import os
import ssl
import certifi
from pathlib import Path
from dotenv import load_dotenv

# ======================================================
# 🌟 環境變數與 SSL 設定
# ======================================================
load_dotenv()  # 載入與 app 資料夾同層的 .env 檔案

# Google Gemini API 金鑰
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

# 設定 SSL 憑證（確保 Google API 可正確使用 HTTPS）
os.environ["GRPC_DEFAULT_SSL_ROOTS_FILE_PATH"] = certifi.where()
ssl._create_default_https_context = ssl._create_unverified_context
print("✅ Django 啟動時載入 SSL 憑證設定")

# ======================================================
# 🌟 專案基本設定
# ======================================================
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-secret-key')
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')]

# ======================================================
# 🌟 INSTALLED_APPS
# ======================================================
INSTALLED_APPS = [
    # Django 內建 apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ✅ 加入 humanize
    'django.contrib.humanize',

    # 你的自訂 app
    'app',
]

# ======================================================
# 🌟 MIDDLEWARE
# ======================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'set.urls'

# ======================================================
# 🌟 TEMPLATES
# ======================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 模板資料夾
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'set.wsgi.application'

# ======================================================
# 🌟 資料庫設定
# ======================================================
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': BASE_DIR / os.getenv('DB_NAME', 'db.sqlite3'),
    }
}

# ======================================================
# 🌟 密碼驗證
# ======================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ======================================================
# 🌟 國際化與時區
# ======================================================
LANGUAGE_CODE = 'zh-hant'
TIME_ZONE = 'Asia/Taipei'
USE_I18N = True
USE_TZ = True

# ======================================================
# 🌟 靜態檔設定
# ======================================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# ======================================================
# 🌟 預設主鍵
# ======================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ======================================================
# 🌟 自訂變數
# ======================================================
GOOGLE_API_KEY = GEMINI_API_KEY  # 統一命名方便 views 使用



# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# ✅ 加這行：Render 部署需要一個明確的 STATIC_ROOT
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
=======
"""
Django settings for set project.
Generated by 'django-admin startproject' using Django 5.0.
"""
import os
import ssl
import certifi
from pathlib import Path
from dotenv import load_dotenv

# ======================================================
# 🌟 環境變數與 SSL 設定
# ======================================================
load_dotenv()  # 載入與 app 資料夾同層的 .env 檔案

# Google Gemini API 金鑰
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

# 設定 SSL 憑證（確保 Google API 可正確使用 HTTPS）
os.environ["GRPC_DEFAULT_SSL_ROOTS_FILE_PATH"] = certifi.where()
ssl._create_default_https_context = ssl._create_unverified_context
print("✅ Django 啟動時載入 SSL 憑證設定")

# ======================================================
# 🌟 專案基本設定
# ======================================================
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-secret-key')
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')]

# ======================================================
# 🌟 INSTALLED_APPS
# ======================================================
INSTALLED_APPS = [
    # Django 內建 apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ✅ 加入 humanize
    'django.contrib.humanize',

    # 你的自訂 app
    'app',
]

# ======================================================
# 🌟 MIDDLEWARE
# ======================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'set.urls'

# ======================================================
# 🌟 TEMPLATES
# ======================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 模板資料夾
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'set.wsgi.application'

# ======================================================
# 🌟 資料庫設定
# ======================================================
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': BASE_DIR / os.getenv('DB_NAME', 'db.sqlite3'),
    }
}

# ======================================================
# 🌟 密碼驗證
# ======================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ======================================================
# 🌟 國際化與時區
# ======================================================
LANGUAGE_CODE = 'zh-hant'
TIME_ZONE = 'Asia/Taipei'
USE_I18N = True
USE_TZ = True

# ======================================================
# 🌟 靜態檔設定
# ======================================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# ======================================================
# 🌟 預設主鍵
# ======================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ======================================================
# 🌟 自訂變數
# ======================================================
GOOGLE_API_KEY = GEMINI_API_KEY  # 統一命名方便 views 使用
>>>>>>> origin/main
