"""
Django settings for set project.

Generated by 'django-admin startproject' using Django 5.0.
"""

from pathlib import Path

# 專案目錄定義，這對於靜態檔案設定很重要
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'zu2wi-7wskg=hpz+p1tj^qh#twc3fto*o98u912ht9ueoa1_et'
# ⚠️ 安全設定 ⚠️
# 由於您遇到 ALLOWED_HOSTS 錯誤，我們將 DEBUG 設定為 True
DEBUG = True

# 由於 DEBUG = True，這裡可以留空
ALLOWED_HOSTS = [] 

# 這是安裝 Django 時自動生成的密鑰，通常不會顯示出來
# SECRET_KEY = '...' 


# 1. 🌟 INSTALLED_APPS (已修復 ContentTypes 錯誤) 🌟
INSTALLED_APPS = [
    # 核心 Django 應用程式
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',   
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 您的自定義 App
    'app', 
]


# 2. 🌟 MIDDLEWARE (已修復 E408, E409, E410 錯誤) 🌟
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Session, Auth, Message 相關中間件是 Admin 啟動的關鍵
    'django.contrib.sessions.middleware.SessionMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware', 
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 路由設定
ROOT_URLCONF = 'set.urls'


# 3. 🌟 TEMPLATES (已修復 E403 錯誤) 🌟
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], 
        # 確保這個是 True，讓 Django 找到 App 裡的 'templates' 資料夾
        'APP_DIRS': True, 
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# WSGI_APPLICATION = 'set.wsgi.application' (保持不變)


# 資料庫設定 (通常保持預設的 SQLite)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# 密碼驗證 (保持不變)
AUTH_PASSWORD_VALIDATORS = [
    # ... (保持預設)
]


# 國際化和時區設定
LANGUAGE_CODE = 'zh-hant'  # 建議使用中文
TIME_ZONE = 'Asia/Taipei'   # 或 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True


# 4. 靜態檔案設定
# 瀏覽器用來存取靜態檔案（如 CSS、圖片）的 URL
STATIC_URL = 'static/'

# （可選）如果未來要部署，這是收集靜態檔案的目錄
# import os
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

# 預設主鍵類型 (保持不變)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'